### ISSUE TITLE
[CRITICAL] Security issue

### ISSUE THREAD

**Issue by 0xecute** [tillkuhn/visualCaptcha-java-rest#3]
Hi,
Your captcha can be easily bypass.

If `GET /start/:howmany` is called by the browser, the client can edit the request and send:
`GET /start/1`.
Then the captcha is useless because there is only one choice possible, so it is easy to write a script to bypass your captcha.

Best regards,

0xecute

**Comment by tillkuhn** [comment]
Good point, the server should at least verify that the _howmany_ param is > 1. Feel free to create a pull request if you already have a fix, otherwhise I'll try to add this in the next days!

// Till

**Comment by 0xecute** [comment]
Sorry I don't have any fix.

Best,
0xecute
